### ISSUE TITLE
Generate parts on Linux without Fusion360

### ISSUE THREAD

**Issue by Baehn** [JesusFreke/lalboard#18]
Hello,

I would like to generate all parts (i.e. corresponding stl files) on my linux machine which also means that I don't have access to Fusion360. Is this possible? For example, I tried to run "parts/cluster/cluster.py" with "lalboard.Lalboard()" as a context but this is not working.

I also tried running "run()" in  "parts/export_parts.py" but I get the following errors:
<pre>
Running central_pcb_sketch
Traceback (most recent call last):
  File "/home/chbaeh/projects/cc2/parts/fscad/fscad.py", line 4466, in run_design
    setup_document(document_name)
  File "/home/chbaeh/projects/cc2/parts/fscad/fscad.py", line 4415, in setup_document
    for document in app().documents:
TypeError: 'Documents' object is not iterable

Traceback (most recent call last):
  File "/home/chbaeh/projects/cc2/parts/export_parts.py", line 75, in run
    if len(root().sketches) != 1:
TypeError: object of type 'Sketches' has no len()
</pre>

(great work btw :smiley:  )

**Comment by JesusFreke** [comment]
It's not possible, unless you're able to run fusion 360 in wine or in a VM or something.

**Comment by JesusFreke** [comment]
@claussen reimplemented the parts in onshape, and has been doing a lot of work on the design though

**Comment by claussen** [comment]
@JesusFreke , Looks like a fun project, but I think you are giving me credit for work done by someone else.

**Comment by JesusFreke** [comment]
oops, sorry about that! I meant @morganvenable. I believe he goes by claussen elsewhere, haha

**Comment by morganvenable** [comment]
Too late to the short username party here 😅

**Comment by claussen** [comment]
It's all good.  Just want to ensure credit given where it's due.

**Comment by Baehn** [comment]
@morganvenable: are your parts available somewhere?

**Comment by scruper** [comment]
Is it worthwhile to reimplement 3D model generation with CadQuery? It might be much easier for newcomers to make adjustments. What do you think?

**Comment by morganvenable** [comment]
Not to me personally, but I bet someone would appreciate it.  The fine
details I've had to get into in procedural CAD would've been pretty hairy
in SCAD, and configuration management is pretty heavy too.  Any workflow
that doesn't give live, direct editing of the geometry you're looking at
would've multiplied my work effort and time by... 10x?  Soooooo many little
fiddly bits.

**Comment by Ben-PH** [comment]
For this to be a truly FOSS project, the modelling will need to be done in a FOSS software as well. onshape and f360 are no-go's. Given the openSCAD diffuculties by nature of this project, maybe FreeCAD would be the way to go?

I'm inclined to do some sort of fork and bring this up in freeCAD. I hate FreeCAD for its usability, but beats having this project beholden to closed sauce.

**Comment by JesusFreke** [comment]
Be my guest ;)

**Comment by madnificent** [comment]
@Ben-PH Did you start on a FreeCAD conversion?

**Comment by duchainer** [comment]
> Is it worthwhile to reimplement 3D model generation with CadQuery? It might be much easier for newcomers to make adjustments. What do you think?

Yeah, and there are GUI for it now, like https://github.com/CadQuery/CQ-editor, if that can help anyone finding an open source home to port the design.
( Not familiar with any of this yet, just nice to see sharing of alternate keyboard/key-entry designs, thanks for the lalboard share :D )
